from flask import Flask, render_template, request, jsonify
import os
from datetime import datetime

app = Flask(__name__)

@app.route('/')
def index():
      return '''
          <!DOCTYPE html>
              <html lang="ar" dir="rtl">
                  <head>
                          <meta charset="UTF-8">
                                  <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                          <title>النظام المالي الذكي - شركة الطباعة الرقمية</title>
                                                  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
                                                          <style>
                                                                      body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }
                                                                                  .header { background: linear-gradient(45deg, #4CAF50, #45a049); color: white; padding: 20px; border-radius: 15px; text-align: center; margin-bottom: 30px; }
                                                                                              .feature-card { background: white; border-radius: 15px; padding: 25px; margin: 15px 0; box-shadow: 0 5px 15px rgba(0,0,0,0.08); }
                                                                                                      </style>
                                                                                                          </head>
                                                                                                              <body>
                                                                                                                      <div class="container mt-4">
                                                                                                                                  <div class="header">
                                                                                                                                                  <h1>🚀 النظام المالي الذكي</h1>
                                                                                                                                                                  <p>نظام ذكي لمعالجة الفواتير وتحليل المعاملات البنكية</p>
                                                                                                                                                                              </div>
                                                                                                                                                                                          
                                                                                                                                                                                                      <div class="row">
                                                                                                                                                                                                                      <div class="col-md-6">
                                                                                                                                                                                                                                          <div class="feature-card">
                                                                                                                                                                                                                                                                  <h3>📄 معالج الفواتير الذكي</h3>
                                                                                                                                                                                                                                                                                          <p>رفع وتحليل الفواتير تلقائياً باستخدام الذكاء الاصطناعي</p>
                                                                                                                                                                                                                                                                                                                  <button class="btn btn-success">رفع فاتورة</button>
                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                      <div class="col-md-6">
                                                                                                                                                                                                                                                                                                                                                                                                          <div class="feature-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>📊 محلل المعاملات البنكية</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>تحليل كشوف الحساب البنكي وإنشاء تقارير مالية</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button class="btn btn-primary">رفع كشف حساب</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="feature-card mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>✅ النظام يعمل بنجاح!</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>تم نشر النظام المالي الذكي بنجاح على Render</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p><strong>التاريخ:</strong> ''' + datetime.now().strftime('%Y-%m-%d %H:%M:%S') + '''</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p><strong>الحالة:</strong> متصل ويعمل</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '''

@app.route('/api/status')
def status():
      return jsonify({
                'status': 'running',
                'timestamp': datetime.now().isoformat(),
                'message': 'النظام المالي الذكي يعمل بنجاح'
      })

if __name__ == '__main__':
      port = int(os.environ.get('PORT', 5000))
      app.run(host='0.0.0.0', port=port, debug=False)
